### ISSUE TITLE
User will be able to register a new account

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#1]
* ID (not shown on UI), Username, email, password (other fields optional)
* Password field should be 60 characters
* Passwords should be hashed (plain text passwords lose points)
* Email should be unique
* Username should be unique
* Form should have proper validations/checks for legitimate data
      * Email validation
      * Username validation (length/required)
      * Password validation (length minimum)
      * Confirm password match
* System should let user know if username or email is taken and allow the user to correct the error without wiping the form

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/6045431decdc20840754fee6f441cdabec6fd2de#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/6045431decdc20840754fee6f441cdabec6fd2de#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01
