### ISSUE TITLE
User will be able to logout

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#3]
* Logging out will redirect to login page
* User should see a message that they’ve successfully logged out
* Session should be destroyed (so the back button doesn’t allow them back in)

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/9dfe45cace7732089269af5a432a906666c74141#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/9dfe45cace7732089269af5a432a906666c74141#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01
