### ISSUE TITLE
Basic security rules implemented

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#4]
* Function to check if user is logged in
* Function should be called on appropriate pages that only allow logged in users

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/9dfe45cace7732089269af5a432a906666c74141#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/9dfe45cace7732089269af5a432a906666c74141#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01
