### ISSUE TITLE
Basic Roles implemented

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#5]
* Have a Roles table	(id, name, description, active)
* Have a User Roles table (id, user_id, role_id, created)
* Include a function to check if a user has a specific role (we won’t use it for this milestone but it should be usable in the future)

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/18d94df887874b4653a4e2e78702c01c2d1b1bf7#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/18d94df887874b4653a4e2e78702c01c2d1b1bf7#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01
