### ISSUE TITLE
Site should have basic styles/theme applied

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#6]

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/8fa790cd7f724ebf72bd5646b33400382b48fb8c#diff-ee45eda4c69884dc42548e1ff3a0801c4038f45313ee03cd399217301f9070a1

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/8fa790cd7f724ebf72bd5646b33400382b48fb8c#diff-ee45eda4c69884dc42548e1ff3a0801c4038f45313ee03cd399217301f9070a1
