### ISSUE TITLE
Any technical errors or debug output displayed will result in a loss of points

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#7]

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/991cf2e907a594ce34860e092ecacdfc23220ee0#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/991cf2e907a594ce34860e092ecacdfc23220ee0#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01
