### ISSUE TITLE
User will be able to edit their profile

### ISSUE THREAD

**Issue by eric-delarosa** [eddlr98/IT202011#9]
* Changing username/email should properly check to see if it’s available before allowing the change
* Any other fields should be properly validated
* Allow password reset (only if the existing correct password is provided)

**Comment by eddlr98** [comment]
https://github.com/eddlr98/IT202011/commit/6045431decdc20840754fee6f441cdabec6fd2de#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01

**Comment by eric-delarosa** [comment]
https://github.com/eddlr98/IT202011/commit/6045431decdc20840754fee6f441cdabec6fd2de#diff-244210e48437b6556980a70249a99369934a352429034cef9d7bd253b3bf2c01
